### ISSUE TITLE
toggling it twice plays the sound twice

### ISSUE THREAD

**Issue by U5B** [asdfcube/ASDFmod-BPS#2]
if you do /bps twice in-game and then log out, the sounds are duplicated.

optionally, have it show if it is enabled or disabled with /bps and then have a new command called /bps toggle that actually toggles the sounds

or just have the user remove the mod if they want to remove client-side sounds

**Comment by U5B** [comment]
Also now with the mod removed, the server-side sound is duplicated twice, even with the mod removed

Note: that has stopped, but now with the mod in my mods folder, the client-side sound and server-side sound is sent

**Comment by asdfcube** [comment]
> if you do /bps twice in-game and then log out, the sounds are duplicated.

how exactly did you do it? also how high is your ping?

**Comment by asdfcube** [comment]
> if you do /bps twice in-game and then log out, the sounds are duplicated.

How exactly did you do it? It is possible for the sound from server not being filtered out if they have custom sound for block placing. (see below)

> Also now with the mod removed, the server-side sound is duplicated twice, even with the mod removed

What do you mean by removing the mod?

> but now with the mod in my mods folder, the client-side sound and server-side sound is sent

If you play on some servers with custom block placing sound, the mod might not be compatible as either the server sends a sound packet at a different location or sends it twice. For example, bridging practice in bedwarspractice.club. 
![SharedScreenshot](https://user-images.githubusercontent.com/36262524/106409660-0060d380-647c-11eb-8dcd-8bf8db444337.jpg)

**Comment by asdfcube** [comment]
> optionally, have it show if it is enabled or disabled with /bps and then have a new command called /bps toggle that actually toggles the sounds

I have taken that into account and will implement your advice :)

**Comment by U5B** [comment]
I should've specified for bedwarspractice.club but forgot. Anyway the sound duplication only seems to happen on bedwarspractice bridging, but no other gamemodes on that. Thanks for clarifying.

**Comment by asdfcube** [comment]
> I should've specified for bedwarspractice.club but forgot. Anyway the sound duplication only seems to happen on bedwarspractice bridging, but no other gamemodes on that. Thanks for clarifying.

I have talked to the owner/developer of bedwarspractice.club and he said it is intensional, so I am working on detecting their doubled sound packets, but for those servers with different sound locations, its not feasible to filter in such a small-scaled mod.
